ekyna_backend:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dashboard
        permanent: true

ekyna_backend_dashboard:
    pattern:  /dashboard
    methods: [GET]
    defaults: { _controller: EkynaBackendBundle:Dashboard:index }

ekyna_backend_page:
    resource: "@EkynaBackendBundle/Resources/config/routing/backend/page.yml"
    prefix:   /pages

ekyna_backend_security_login:
    pattern: /login
    methods: [GET]
    defaults: { _controller: EkynaBackendBundle:Security:login }

ekyna_backend_security_check:
    pattern: /login-check
    methods: [POST]
    defaults: { _controller: EkynaBackendBundle:Security:checkAction }

ekyna_backend_security_logout:
    pattern: /logout